version: '3.1'
services:
  database:
    env_file:
      - ./dockerComposeEnv/database.env
    image: go_database
    container_name: gameOne_database
    environment: {}
    build:
      context: ./database/docker/src
      dockerfile: Dockerfile
    ports:
      - 9000:5432
    restart: always
    stdin_open: true
    tty: true
    logging:
      options:
        max-size: "10m"
        max-file: "10"